account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = "account"
urlpatterns = [
    path('login', auth_views.LoginView.as_view(next_page=reverse_lazy("forum:index")), name="login"),
    path('logout', auth_views.LogoutView.as_view(next_page=reverse_lazy("forum:index")),name="logout"),
    path('signup', views.signup, name="signup"),
    path('settings', views.settings, name="settings"),
    path('passwordchange', views.passwordchange, name="passwordchange"),
    path('deleteuser', views.deleteuser, name="deleteuser")
]

forum/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views

from . import views

app_name = "forum"
urlpatterns = [
    path('', views.forumindex, name="index"),
    path('<str:username>', views.userpage, name="userpage"),
    path('<str:username>/with_replies', views.userpagewithreplies, name="userpagewithreplies"),
    path('messages/<int:msgid>', views.messageinfo, name="messageinfo"),
    path('messages/rate/<int:msgid>', views.ratepage, name="ratepage"),
    path('messages/ratings/<int:msgid>', views.ratingspage, name="ratingspage"),
    path('messages/create', views.createmessage, name="createmessage"),
    path('messages/create/<int:msgid>', views.createmessage, name="createmessage"),
    path('messages/read/<int:msgid>', views.readmessage, name="readmessage"),
    path('messages/update/<int:msgid>', views.updatemessage, name="updatemessage"),
    path('messages/delete/<int:msgid>', views.deletemessage, name="deletemessage")
]

project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from django.views.defaults import page_not_found, server_error, permission_denied, bad_request

def custom_page_not_found(request):
    return page_not_found(request, None)

def custom_permission_denied(request):
    return permission_denied(request, None)

def custom_bad_request(request):
    return bad_request(request, None)


urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy("forum:index"), permanent=True)),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls'), name="account"),
    path('forum/', include('forum.urls'), name="forum"),
    path("404/", custom_page_not_found),
    path("500/", server_error),
    path("403/", custom_permission_denied),
    path("400/", custom_bad_request)
]

forum/models.py
from django.db import models
from django.conf import settings
from datetime import datetime

# Create your models here.

class Message(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    reply_to = models.ForeignKey("Message", on_delete=models.SET_NULL, blank=True, null=True)
    content = models.TextField()
    pub_date = models.DateTimeField(blank=True, auto_now_add=True)
    edit_date = models.DateTimeField(blank=True, null=True, default=None)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="liking")
    dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="disliking")
    is_active = models.BooleanField(default=True)

    #TODO: Do the equivalent of select_related(reply_to) using raw sql queries

    #Traverse through specified number of parent messages and aggregate them recursively
    def get_replied_messages(self,n):
        return Message.objects.raw(
            'WITH RECURSIVE replies_to(id) AS (\
            SELECT forum_message.reply_to_id \
            FROM forum_message \
            WHERE forum_message.id = %s \
            UNION \
            SELECT forum_message.reply_to_id \
            FROM forum_message, replies_to \
            WHERE forum_message.id = replies_to.id \
            LIMIT %s ) \
            SELECT * FROM forum_message \
            WHERE forum_message.id IN replies_to', [self.pk, n])

    #Traverse through all parent messages and aggregate them recursively
    def get_all_replied_messages(self):
        return Message.objects.raw(
            'WITH RECURSIVE replies_to(id) AS (\
            SELECT forum_message.reply_to_id \
            FROM forum_message \
            WHERE forum_message.id = %s \
            UNION \
            SELECT forum_message.reply_to_id \
            FROM forum_message, replies_to \
            WHERE forum_message.id = replies_to.id ) \
            SELECT * FROM forum_message \
            WHERE forum_message.id IN replies_to', [self.pk])

    def soft_delete(self, commit=True):
        """Does not actually delete the message, sets it as inactive"""
        self.is_active = False
        if commit:
            self.save()
        return self

    def updateandsave(self, content, commit=True):
        self.content = content
        self.edit_date = datetime.now()
        if commit:
            self.save()
        return self

    def likes_count(self):
        return str(self.likes.count())

    def dislikes_count(self):
        return str(self.dislikes.count())

    def __str__(self):
        return f"{self.id} - {self.content[:20]}"

forum/forms.py
from django import forms

from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["content"]

class RatingForm(forms.Form):
    CHOICES = (
        ("none", "None"),
        ("like", "👍"),
        ("dislike", "👎")
    )
    rating = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

forum/views.py
from math import ceil
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseForbidden, HttpResponseNotAllowed, HttpResponseBadRequest, Http404
from .models import Message
from .forms import MessageForm, RatingForm

# Create your views here.

@login_required
def ratepage(request, msgid):
    message = get_object_or_404(Message, id=msgid)
    if request.method == 'POST':
        ratingform = RatingForm(request.POST)
        if ratingform.is_valid():
            rating = ratingform.cleaned_data["rating"]
            user = request.user
            match rating:
                case "like":
                    if user.disliking.filter(id=msgid):
                        user.disliking.remove(message)
                    user.liking.add(message)
                    return redirect(request.META.get('HTTP_REFERER'))
                case "dislike":
                    message = get_object_or_404(Message, id=msgid)
                    if user.liking.filter(id=msgid):
                        user.liking.remove(message)
                    user.disliking.add(message)
                    return redirect(request.META.get('HTTP_REFERER'))
                case "none":
                    if user.liking.filter(id=msgid):
                        user.liking.remove(message)
                    if user.disliking.filter(id=msgid):
                        user.disliking.remove(message)
                    return redirect(request.META.get('HTTP_REFERER'))

                case _:
                    return HttpResponseBadRequest()
        else:
            return HttpResponseBadRequest()
    else:
        return HttpResponseNotAllowed(["POST"])

def ratingspage(request, msgid):
    message = get_object_or_404(Message, id=msgid)
    messagelikes = message.likes.all()
    messagedislikes = message.dislikes.all()
    return render(request, "forum/ratingspage.html", {"messagelikes": messagelikes,
                                                 "messagedislikes": messagedislikes})



@login_required
def createmessage(request, msgid=None):
    if request.method == 'POST':
        repliedmessage = get_object_or_404(Message, id=msgid) if msgid else None
        messageform = MessageForm(request.POST)
        if messageform.is_valid():
            receivedmessage = messageform.save(commit=False)
            receivedmessage.author = request.user
            receivedmessage.reply_to = repliedmessage
            receivedmessage.save()
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            HttpResponseBadRequest()
    else:
        return HttpResponseNotAllowed(["POST"])

def readmessage(request, msgid):
    if request.method == 'GET' or 'HEAD':
        try:
            message = Message.objects.select_related('reply_to').get(id=msgid)
        except Message.DoesNotExist:
            raise Http404("Message does not exist")
        return render(request, "forum/messagedisplay.htmlinc", {"message": message})
    else:
        return HttpResponseNotAllowed(["GET", "HEAD"])

@login_required
def updatemessage(request, msgid):
    if request.method == 'POST':
        message = get_object_or_404(Message, id=msgid)
        if not message.is_active:
            return HttpResponseForbidden()
        if request.user == message.author:
            messageform = MessageForm(request.POST)
            if messageform.is_valid():
                content = messageform.cleaned_data['content']
                message.updateandsave(content)
                return redirect(reverse('forum:userpage', args=[request.user.username]))
            else:
                return HttpResponseBadRequest()
        else:
            return HttpResponseForbidden()
    else:
        return HttpResponseNotAllowed(["POST"])

@login_required
def deletemessage(request, msgid):
    if request.method == 'POST':
        message = get_object_or_404(Message, id=msgid)
        if request.user == message.author:
            message.soft_delete()
            return redirect(reverse('forum:userpage', args=[request.user.username]))
        else:
            return HttpResponseForbidden()
    else:
        return HttpResponseNotAllowed(["POST"])

def forumindex(request):
    currpage = int(request.GET.get("page") or 1)
    messagecount = Message.objects.all().count()
    messages = Message.objects.all().select_related("reply_to").order_by('-id', '-pub_date')[10*(currpage-1):10*currpage]
    pagenum = [*range(1, ceil(messagecount / 10) + 1)]
    return render(request, "forum/index.html", {"messages": messages,
                                                "pagenum": pagenum})

def userpage(request, username):
    userpageowner = get_object_or_404(get_user_model(), username=username)

    messageform = MessageForm() if request.user.is_authenticated else None

    currpage = int(request.GET.get("page") or 1)
    messagecount = userpageowner.message_set.filter(reply_to=None).count()
    messages = userpageowner.message_set.filter(reply_to=None).order_by('-id', '-pub_date')[10*(currpage - 1):10*currpage]
    pagenum = [*range(1, ceil(messagecount / 10) + 1)]

    return render(request, "forum/userpage.html",
                  {"userpageowner": userpageowner,
                   "messages": messages,
                   "messageform": messageform,
                   "pagenum": pagenum})

def userpagewithreplies(request, username):
    userpageowner = get_object_or_404(get_user_model(), username=username)

    messageform = MessageForm() if request.user.is_authenticated else None

    messagecount = userpageowner.message_set.all().count()
    currpage = int(request.GET.get("page") or 1)
    messages = userpageowner.message_set.all().select_related("reply_to").order_by('-id', '-pub_date')[10*(currpage - 1):10*currpage]
    pagenum = [*range(1, ceil(messagecount / 10) + 1)]

    return render(request, "forum/userpage.html",
                  {"userpageowner": userpageowner,
                   "messages": messages,
                   "messageform": messageform,
                   "pagenum": pagenum})

def messageinfo(request, msgid):
    message = get_object_or_404(Message, pk=msgid)

    messagereplyform = MessageForm() if request.user.is_authenticated else None
    messageupdateform = MessageForm(instance=message) if request.user.is_authenticated else None
    ratingform = RatingForm() if request.user.is_authenticated else None

    replies = message.message_set.all().order_by('-id', '-pub_date')
    reply_chain = message.get_all_replied_messages()

    return render(request, "forum/messageinfo.html",
                  {"message": message,
                   "replies": replies,
                   "reply_chain": reply_chain,
                   "messagereplyform": messagereplyform,
                   "messageupdateform": messageupdateform,
                   "ratingform": ratingform})

forum/templates/forum/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<h1>Hello to Forum</h1>

<nav class="pagenavbar">
    {% include 'forum/pagenavigation.htmlinc' with pagenum=pagenum %}
</nav>

<section class="messages-body">
{% for message in messages %}
    <article class="message">
    {% include "forum/messagedisplay.htmlinc" with message=message %}
    </article>
{% endfor %}
</section>

<nav class="pagenavbar">
    {% include 'forum/pagenavigation.htmlinc' with pagenum=pagenum %}
</nav>

</div>
{% endblock content %}

forum/templates/forum/messageinfo.html
{% extends "base.html" %}

{% block content %}

<div class="container">

<h2>Leading Conversation</h2>

<section class="messages-body">
{% for reply in reply_chain %}
    <article class="message">
    {% include "forum/messagedisplay.htmlinc" with message=reply %}
    </article>
{% endfor %}
</section>

<h2 id="message">Message</h2>
<section class="messages-body">
<article class="message">
{% include "forum/messagedisplay.htmlinc" with message=message %}
</article>

{% if user.is_authenticated %}
<details>
    <summary>Rate this message</summary>
    {{ form.name.errors }}
    <form action="{% url 'forum:ratepage' message.id %}" method="POST">
        {{ form.name.errors }}
        {% csrf_token %}
            {{ ratingform.as_div }}
        <button type="submit">Rate</button>
    </form>
</details>
{% endif %}

{% if user.is_authenticated %}
<details>
<summary>Reply here</summary>
<form action="{% url 'forum:createmessage' message.id %}" method="POST">
    {% csrf_token %}
        {{ messagereplyform.as_div }}
    <button type="submit">Reply</button>
</form>
</details>
{% endif %}

{% if user.is_authenticated %}
{% if request.user == message.author %}
<details>
<summary>Update message</summary>
<form action="{% url 'forum:updatemessage' message.id %}" method="POST">
    {% csrf_token %}
        {{ messageupdateform.as_div }}
    <button type="submit">Update</button>
</form>
</details>
{% endif %}
{% endif %}

{% if user.is_authenticated %}
{% if request.user == message.author %}
<details>
<summary>Delete message</summary>
<form action="{% url 'forum:deletemessage' message.id %}" method="POST">
    <label>Are you sure?</label>
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>
</details>
{% endif %}
{% endif %}

</section>

<h2>Replies</h2>
<section class="messages-body">
{% for reply in replies %}
    <article class="message">
    {% include "forum/messagedisplay.htmlinc" with message=reply parent_message=message %}
    </article>
{% endfor %}
</section>

</div>

{% endblock content %}

forum/templates/forum/ratingspage.html
{% extends "base.html" %}

{% block content %}

<div class="container">

    {% if not messagelikes and not messagedislikes %}
    <h2>There haven't been any rating on this message yet</h2>
    {% else %}
    <h2>All ratings and their corresponding users</h2>
    <ul class="info">
    {% for liker in messagelikes %}
        <li><a href="{% url 'forum:userpage' liker.get_username %}">@{{ liker }}:</a> 👍</li>
    {% endfor %}
    {% for disliker in messagedislikes %}
        <li><a href="{% url 'forum:userpage' disliker.get_username %}">@{{ disliker }}:</a> 👎</li>
    {% endfor %}
    </ul>
    {% endif %}

</div>

{% endblock content %}

forum/templates/forum/userpage.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<h1>Page Owner</h1>
<ul class="info">
{% include 'account/userinfo.htmlinc' with user=userpageowner %}
</ul>



<div class="button-container">
    <a href="{% url 'forum:userpage' userpageowner.username %}"><button>Messages</button></a>
    <a href="{% url 'forum:userpagewithreplies' userpageowner.username %}"><button>Messages &amp; Replies</button></a>
    {% if user.id == userpageowner.id %}
    <a href="{% url 'account:settings' %}"><button>Settings</button></a>
    {% endif %}
</div>

{% if user.get_username == userpageowner.username %}
<h2>Your messages</h2>
{% else %}
<h2>Users messages</h2>
{% endif %}

<nav class="pagenavbar">
    {% include 'forum/pagenavigation.htmlinc' with pagenum=pagenum %}
</nav>

<section class="messages-body">

{% if user.is_authenticated %}
{% if user.get_username == userpageowner.username %}
{% if messageform %}
{# <p>Create new message</p> #}
<details>
<summary>Create new message</summary>
<form action="{% url 'forum:createmessage' %}" method="POST">
    {% csrf_token %}
    {{ messageform.as_div }}
    <button type="submit">Send</button>
</form>
</details>
{% endif %}
{% endif %}
{% endif %}

{% for message in messages %}
    <article class="message">
    {% include "forum/messagedisplay.htmlinc" with message=message %}
    </article>
{% endfor %}
</section>

<nav class="pagenavbar">
    {% include 'forum/pagenavigation.htmlinc' with pagenum=pagenum %}
</nav>
</div>

{% endblock content %}