account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = "account"
urlpatterns = [
    path('login', auth_views.LoginView.as_view(next_page=reverse_lazy("forum:index")), name="login"),
    path('logout', auth_views.LogoutView.as_view(next_page=reverse_lazy("forum:index")),name="logout"),
    path('signup', views.signup, name="signup"),
    path('settings', views.settings, name="settings"),
    path('passwordchange', views.passwordchange, name="passwordchange"),
    path('deleteuser', views.deleteuser, name="deleteuser")
]

forum/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views

from . import views

app_name = "forum"
urlpatterns = [
    path('', views.forumindex, name="index"),
    path('<str:username>', views.userpage, name="userpage"),
    path('<str:username>/with_replies', views.userpagewithreplies, name="userpagewithreplies"),
    path('messages/<int:msgid>', views.messageinfo, name="messageinfo"),
    path('messages/rate/<int:msgid>', views.ratepage, name="ratepage"),
    path('messages/ratings/<int:msgid>', views.ratingspage, name="ratingspage"),
    path('messages/create', views.createmessage, name="createmessage"),
    path('messages/create/<int:msgid>', views.createmessage, name="createmessage"),
    path('messages/read/<int:msgid>', views.readmessage, name="readmessage"),
    path('messages/update/<int:msgid>', views.updatemessage, name="updatemessage"),
    path('messages/delete/<int:msgid>', views.deletemessage, name="deletemessage")
]

project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from django.views.defaults import page_not_found, server_error, permission_denied, bad_request

def custom_page_not_found(request):
    return page_not_found(request, None)

def custom_permission_denied(request):
    return permission_denied(request, None)

def custom_bad_request(request):
    return bad_request(request, None)


urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy("forum:index"), permanent=True)),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls'), name="account"),
    path('forum/', include('forum.urls'), name="forum"),
    path("404/", custom_page_not_found),
    path("500/", server_error),
    path("403/", custom_permission_denied),
    path("400/", custom_bad_request)
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Project</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <header id="global-header">
        <div id="logo"><a href="{% url 'forum:index' %}">Forumsite</a></div>
        <div id="user-box">
        {% if request.user.is_authenticated %}
            <p id="hello-user">Hello <a href="{% url 'forum:userpage' request.user.get_username %}">{{ request.user.get_username }}</a></p>
            <div class="button-container">
                {# The following button does not work after Django version 5.0 due to support for logging out on GET requests being depricated. #}
                {# https://docs.djangoproject.com/en/4.2/topics/auth/default/#django.contrib.auth.views.LogoutView #}
                <a href="{% url 'account:logout' %}?next={{ request.path }}"><button>Logout</button></a>
            </div>
        {% else %}
            <p id="hello-user">Hello guest</p>
            <div class="button-container">
            {% url 'account:login' as loginurl %}
            {% url 'account:signup' as signupurl %}
            {% if request.path != loginurl %}
            <a href="{% url 'account:login' %}?next={{ request.path }}"><button>Login</button></a>
            {% endif %}
            {% if request.path != signupurl %}
            <a href="{% url 'account:signup' %}?next={{ request.path }}"><button>Signup</button></a>
            {% endif %}
            </div>
        {% endif %}
        </div>
    </header>
{% block content %}

{% endblock content %}

<footer id="main-footer">
    <p>Copyright &copy; 2023 SisbimProject</p>
</footer>

</body>
</html>

templates/test.html
{% extends "base.html" %}

{% block content %}
<h1>Hello World</h1>
{% endblock %}